version: '2.32.0'
services:
  nginx:
    container_name: nginx
    build : ./requirements/nginx/.
    init: true
    ports:
      - "443:443"
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    init: true

