networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    init: true
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - 3306
    restart: always
  wordpress:
    container_name:  wordpress
    build: ./requirements/wordpress/.
    init: true
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordPress:/var/www/html
    expose:
      - 9000
    restart: always
  nginx:
      container_name: nginx
      build: ./requirements/nginx/.
      init: true
      env_file:
        - .env
      ports:
        - "443:443"
      depends_on:
        - wordpress
      networks:
        - inception
      volumes:
        - wordPress:/var/www/html
      restart: always

volumes:
  wordPress:
  mariadb:
