networks:
  inception:
    driver: bridge

services:
  redis:
    container_name: redis
    build: ./requirements/bonus/redis-cache/.
    init: true
    networks:
      - inception
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    init: true
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb-volumes:/var/lib/mysql
    expose:
      - 3306
    restart: always
  wordpress:
    container_name:  wordpress
    build: ./requirements/wordpress/.
    init: true
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
    volumes:
      - wordpress-volumes:/var/www/html
    expose:
      - 9000
    restart: always
  nginx:
      container_name: nginx
      build: ./requirements/nginx/.
      init: true
      env_file:
        - .env
      ports:
        - "443:443"
      depends_on:
        - wordpress
      networks:
        - inception
      volumes:
        - wordpress-volumes:/var/www/html
      restart: always
  ftp:
      container_name: ftp
      build: ./requirements/bonus/FTP/
      init: true
      env_file:
        - .env
      depends_on:
        - wordpress
      ports:
        - "21:21"
        - "40000-40010:40000-40010"
      networks:
        - inception
      volumes:
        - wordpress-volumes:/var/www/html
      restart: always
  adminer:
    container_name: adminer
    build: ./requirements/bonus/Adminer/.
    init: true
    ports:
      - "8080:8080"
    networks:
      - inception
volumes:
  mariadb-volumes:
    name: mariadb-volumes
    driver: local
    driver_opts:
      device: /home/hibouzid/data/
      o: bind
      type: none
  wordpress-volumes:
    name: wordpress-volumes
    driver: local
    driver_opts:
      device: /home/hibouzid/data/
      o: bind
      type: none
