services:
  mariadb:
    build: ./requirements/mariadb/.
    init: true
    env_file:
      - .env
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress/.
    init: true
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception

networks:
  inception:
    driver: bridge
