networks:
  inception:
    driver: bridge

services:
  mariadb:
    build: ./requirements/mariadb/.
    init: true
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - 3306
  wordpress:
    build: ./requirements/wordpress/.
    init: true
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordPress:/var/www/wordPress
    expose:
      - 9000


volumes:
  wordPress:
  mariadb:
